export const ANALYTICS_EVENT_TYPE = {
  PRODUCT_VIEWED: "PRODUCT_VIEWED",
  CATEGORY_VIEWED: "CATEGORY_VIEWED",
  ADDED_TO_CART: "ADDED_TO_CART",
  REMOVED_FROM_CART: "REMOVED_FROM_CART",
  BUY_NOW_CLICKED: "BUY_NOW_CLICKED",
  ORDER_COMPLETED: "ORDER_COMPLETED",
} as const;

export const ANALYTICS_SOURCE_TYPE = {
  PRODUCT_DETAILS: "PRODUCT_DETAILS",
  CATEGORY: "CATEGORY",
  CART: "CART",
  CHECKOUT:"CHECKOUT"
};
