export const CAMPAIGN_TYPE = {
  FLASH_SALE: "FLASH_SALE",
  SEASONAL_SALE: "SEASONAL_SALE",
  CLEARANCE: "CLEARANCE",
  CATEGORY_SALE: "CATEGORY_SALE",
  TIME_WINDOW_SALE: "TIME_WINDOW_SALE",
  FESTIVAL_SALE: "FESTIVAL_SALE",
  PERSONALIZED: "PERSONALIZED",
  BANNER_PROMOTION: "BANNER_PROMOTION",
  CUSTOM: "CUSTOM",
} as const;

export const SCOPE_TYPE = {
  ALL: "ALL",
  CATEGORY: "CATEGORY",
  PRODUCT: "PRODUCT",
} as const;

export const CATEGORY_LEVEL = {
  MAIN: "MAIN",
  SUB: "SUB",
  SUB_SUB: "SUB_SUB",
} as const;

export const DISCOUNT_TYPE = {
  FIXED: "FIXED",
  PERCENTAGE: "PERCENTAGE",
} as const;

export const SORTING_STRATEGY = {
  HIGH_DISCOUNT: "HIGH_DISCOUNT",
  LOW_PRICE: "LOW_PRICE",
  HIGH_PRICE: "HIGH_PRICE",
  BEST_SELLING: "BEST_SELLING",
  HIGHEST_RATED: "HIGHEST_RATED",
  NEWEST: "NEWEST",
  STOCK_CLEARANCE: "STOCK_CLEARANCE",
} as const;
